import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Grid, Stack } from '@mui/material'
import Link from 'next/link';
import Navbar from '../components/Navbar';
import { FETCHPOST } from '../query';
import {motion} from 'framer-motion'
import { gql, useQuery } from '@apollo/client'
import { client } from './_app';
import MediaCard from '../components/Components/Card';

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={ `bg-[#171d24] min-h-screen emeke max-w-[100vw] mx-auto ${styles.emeke}`}>
        <div>
          <Navbar />
          <div className='w-[90%] mx-auto grid place-items-center h-[80vh]'>
            <Grid container spacing={2} justifyContent='space-between' alignItems='center'>
              <Grid item xs={12} md={6}>
                <motion.div 
                initial={{x:"-100vw"}}
                transition={{type:"spring",duration:1.2,stiffness:120}}
                animate={{x:0}}
                >
                  <Stack spacing={3} className='py-8 px-2 md:py-0'>
                    <h1 className='text-white text-[40px] word'>A Social <span className='text-[#3366ff]'>Blogging</span> Platform</h1>
                    <h3 className='text-white text-[25px] word'>The hassle-free blogging platform for Content-Creators, <br /> thought-leaders,engineers and the dev community!</h3>
                    <p className='text-white text-[23px] word'>Share Your Experience / Journey</p>
                    <p></p>
                    <Link href='/register'><span className='rounded-[50px] mb-4  cursor-pointer py-3 px-6 bg-[#3466f6] text-center text-white w-[30%]'>Get Started</span></Link>
                  </Stack>
                </motion.div>
              </Grid>
              <Grid item xs={12} md={6}>
                <img 
                src="/img/home.svg" className='object-cover w-[98%] md:w-full ' />
              </Grid>
            </Grid>
          </div>
        </div>
        <div className='w-4/5 mx-auto  py-32 md:py-24'>
          <Stack alignItems='center' spacing={2} className='text-center'>
            <h2 className='text-[14px] font-mono text-white font-bold'>From the Community</h2>
            <h2 className='text-[22px] font-mono text-[#3366ff] font-extrabold'>Latest Article</h2>
          </Stack>
          <Grid container spacing={3} justifyContent='space-between' alignItems='center' className='py-6'>
            {posts?.map((post) => (
              <Grid item xs={12} md={4} key={post.id}>
                <MediaCard post={post} />
              </Grid>
            ))}
          </Grid>
        </div>
        <div className='p-6 md:py-8 md:px-4'>
          <div className='w-[98%] md:w-4/5 mx-auto rounded-md  bg-[#212c39] px-5 py-10'>
            <Stack spacing={3} justifyContent='space-around' className='text-center'>
              <h1 className='font-bold text-[32px] font-mono text-white'>Coming Soon</h1>
              <h1 className='font-bold text-[32px] font-mono text-white word'>Blogg For <span className='text-[#3366ff]'>Teams</span></h1>
              <h3 className='font-bold text-[18px] font-mono text-[#3366ff] word'>Collaborate with Diffrent People from all over the world on one project</h3>
            </Stack>
          </div>
        </div>
        {/* <Footer /> */}
      </div>

    </div>
  )
}
export const getServerSideProps = async () => {
  const { loading, data: { getPosts: posts } = {}, error } = await client.query({
    query: FETCHPOST
  })


  
  
  // console.log(data)// const data = JSON.parse(localStorage.getItem('user'))
  if (error) {
    console.log(error.response)
  }
  if (posts === undefined) {
    console.log(error)
    return {
      props: {
        posts: 'Post seems to be empty'
      }
    }

  } else {
    return {
      props: {
        posts: posts
      }
    }
  }
}