import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Grid, Stack } from '@mui/material'
import Link from 'next/link';
import Navbar from '../components/Navbar';
import { FETCHPOST } from '../query';
import { motion } from 'framer-motion'
import { gql, useQuery } from '@apollo/client'
import { client } from './_app';
import MediaCard from '../components/Components/Card';
import TextContainer from '../components/Components/TextContainer';

export default function Home({ posts }) {
  return (
    <div className='bg-black min-h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=''>
        <Navbar />
      </div>
      <div className='w-[90%] mx-auto'>
        <motion.div
          initial={{fontSize: '50px' ,opacity:0}}
          animate={{ opacity:1}}
          transition={{ duration: 1.5,delay:0.5 }}
          className='w-2/5  min-h-[70vh] flex flex-col justify-center items-center'>
          <h1 className='text-[150px] font-bold font-mono text-gray-500'>WELCOME TO BLOGG</h1>
        </motion.div>
      </div>

    </div>
  )
}
export const getServerSideProps = async () => {
  const { loading, data: { getPosts: posts } = {}, error } = await client.query({
    query: FETCHPOST
  })




  // console.log(data)// const data = JSON.parse(localStorage.getItem('user'))
  if (error) {
    console.log(error.response)
  }
  if (posts === undefined) {
    console.log(error)
    return {
      props: {
        posts: 'Post seems to be empty'
      }
    }

  } else {
    return {
      props: {
        posts: posts
      }
    }
  }
}